Citizen.CreateThread(function()
    TriggerEvent('chat:addSuggestion', '/HUD', 'Stell das HUD nach deinen Vorlieben ein!')
    -- TriggerEvent('chat:addSuggestion', '/settings', 'Öffne das Einstellungs-Menu')
    -- TriggerEvent('chat:addSuggestion', '/copyhash', 'Hash eines Objektes kopieren')
    -- TriggerEvent('chat:addSuggestion', '/hardfix', 'Behebe Fehler mit deinem Spieler/Charakter/Inventar/Kleidung')
    -- TriggerEvent('chat:addSuggestion', '/fixInv', 'Behebe Probleme mit dem Inventar')
    -- TriggerEvent('chat:addSuggestion', '/fixPhone', 'Behebe Fehler mit deinem Handy')
    -- TriggerEvent('chat:addSuggestion', '/fixSkin', 'Behebe Fehler mit deinem Spieler/Charakter/Inventar/Kleidung')
    -- TriggerEvent('chat:addSuggestion', '/fixPlayer', 'Behebe Fehler mit deinem Spieler/Charakter/Inventar/Kleidung')
    -- TriggerEvent('chat:addSuggestion', '/fixLoc', 'Behebe Fehler mit deinem Spieler/Charakter/Inventar/Kleidung')
    -- TriggerEvent('chat:addSuggestion', '/openf4', 'F4 Menu öffnen')
    -- -- TriggerEvent('chat:addSuggestion', '/getHash', 'Behebe Fehler mit deinem Spieler/Char/Kleidung')
    -- TriggerEvent('chat:addSuggestion', '/guide', 'Öffne unser Guidebook!')
    -- TriggerEvent('chat:addSuggestion', '/guidebook', 'Öffne unser Guidebook!')
    -- -- TriggerEvent('chat:addSuggestion', '/blipmarker', 'Behebe Fehler mit deinem Spieler/Char/Kleidung')
    -- TriggerEvent('chat:addSuggestion', '/fixMe', 'Behebe Fehler mit deinem Spieler/Charakter/Inventar/Kleidung')
    TriggerEvent('chat:addSuggestion', '/fixx', 'Behebe Fehler mit deinem Spieler/Charakter/Inventar/Kleidung')
    -- TriggerEvent('chat:addSuggestion', '/fixAll', 'Behebe Fehler mit deinem Spieler/Charakter/Inventar/Kleidung')
    -- TriggerEvent('chat:addSuggestion', '/propfix', 'Behebe Propfehler mit Hilfe dieses Befehls!')
    -- TriggerEvent('chat:addSuggestion', '/fixprops', 'Behebe Propfehler mit Hilfe dieses Befehls!')
    -- -- TriggerEvent('chat:addSuggestion', '/fixme', 'Behebe Fehler mit deinem Spieler/Char/Kleidung')
end)

--{{ name = 'interior', help = 'Name der Innenreinrichtung' }}